apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: inspector
    secureJsonData:
      password: inspector_pass
    jsonData:
      database: inspections
      sslmode: disable
      maxOpenConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
